### ISSUE TITLE
Access_token error and Python 2.7 support

### ISSUE THREAD

**Issue by arthurp1** [arthurp1/gitsetup#2]
After executing in command line the following error appeared.

Traceback (most recent call last):
  File "/Users/arthur/repos/gitsetup/gitstart.py", line 39, in <module>
    access_token = os.environ['github_access_token']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)

**Comment by adamhipster** [comment]
Fixed issue, submitting PR.

By the way: when you do this command for the 2nd time in a folder that you've already done it in, some stuff may break. I notice that I should have some checks for that.

**Comment by arthurp1** [comment]
Good fix! It works brilliantly.
And yes, the ability to run it a second time in the same folder is an issue. I've added it to the list of suggestions and fixes.

1. Check if script already has been executed in folder. Second time call should propt y/n to overwrite.
2. Github bad credentials issue (during 'curl -u.. ' command) Ask again for password or reset the gitstart process if incorrect.
3. Git clone, no permission to push. Often you github account/collaboration  it will request if you 
4. Standard .gitignore file creation with most common files to be ignored (see attachment) or even build custom .gitignore based on files https://github.com/github/gitignore.
5. Add collaborator
